resolver: lts-6.3
packages:
- '.'
- location:
    git: https://github.com/meditans/preprocessor.git
    commit: 7f596ec5671ae29e42b336bbc703df1ebce03842
  extra-dep: true
extra-deps:
- varying-0.5.0.0
flags: {}
extra-package-dbs: []
